cartesian_planning_server:
  position_threshold: 0.0005
  rotation_threshold: 0.01
  max_sampling_step: 0.05
  max_step_iterations: 600
  damping: 0.0

  robot_base_link: base_link
  end_effector_link: tool0
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
